PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "migrations" ("id" integer primary key autoincrement not null, "migration" varchar not null, "batch" integer not null);
INSERT INTO migrations VALUES(1,'0001_01_01_000000_create_users_table',1);
INSERT INTO migrations VALUES(2,'0001_01_01_000001_create_cache_table',1);
INSERT INTO migrations VALUES(3,'0001_01_01_000002_create_jobs_table',1);
INSERT INTO migrations VALUES(4,'2026_10_01_174312_create_personal_access_tokens_table',1);
INSERT INTO migrations VALUES(5,'2026_10_01_174436_create_notifications_table',1);
INSERT INTO migrations VALUES(6,'2026_10_01_180000_create_roles_table',1);
INSERT INTO migrations VALUES(7,'2026_10_01_180001_add_role_id_and_phone_to_users_table',1);
INSERT INTO migrations VALUES(8,'2026_10_01_180002_create_skills_table',1);
INSERT INTO migrations VALUES(9,'2026_10_01_180003_create_jobs_table',1);
INSERT INTO migrations VALUES(10,'2026_10_01_180004_create_job_skills_table',1);
INSERT INTO migrations VALUES(11,'2026_10_01_180005_create_candidates_table',1);
INSERT INTO migrations VALUES(12,'2026_10_01_180006_create_resumes_table',1);
INSERT INTO migrations VALUES(13,'2026_10_01_180007_create_applications_table',1);
INSERT INTO migrations VALUES(14,'2026_10_01_180008_create_application_status_histories_table',1);
INSERT INTO migrations VALUES(15,'2026_10_01_180009_create_interviews_table',1);
INSERT INTO migrations VALUES(16,'2026_10_01_180010_create_technical_tasks_table',1);
INSERT INTO migrations VALUES(17,'2026_10_01_180011_create_task_submissions_table',1);
INSERT INTO migrations VALUES(18,'2026_10_03_190000_add_performance_indexes_to_tables',1);
INSERT INTO migrations VALUES(19,'2026_10_03_220000_add_attachments_to_technical_tasks_table',2);
CREATE TABLE IF NOT EXISTS "password_reset_tokens" ("email" varchar not null, "token" varchar not null, "created_at" datetime, primary key ("email"));
CREATE TABLE IF NOT EXISTS "sessions" ("id" varchar not null, "user_id" integer, "ip_address" varchar, "user_agent" text, "payload" text not null, "last_activity" integer not null, primary key ("id"));
CREATE TABLE IF NOT EXISTS "cache" ("key" varchar not null, "value" text not null, "expiration" integer not null, primary key ("key"));
CREATE TABLE IF NOT EXISTS "cache_locks" ("key" varchar not null, "owner" varchar not null, "expiration" integer not null, primary key ("key"));
CREATE TABLE IF NOT EXISTS "queue_jobs" ("id" integer primary key autoincrement not null, "queue" varchar not null, "payload" text not null, "attempts" integer not null, "reserved_at" integer, "available_at" integer not null, "created_at" integer not null);
CREATE TABLE IF NOT EXISTS "job_batches" ("id" varchar not null, "name" varchar not null, "total_jobs" integer not null, "pending_jobs" integer not null, "failed_jobs" integer not null, "failed_job_ids" text not null, "options" text, "cancelled_at" integer, "created_at" integer not null, "finished_at" integer, primary key ("id"));
CREATE TABLE IF NOT EXISTS "failed_jobs" ("id" integer primary key autoincrement not null, "uuid" varchar not null, "connection" varchar not null, "queue" varchar not null, "payload" text not null, "exception" text not null, "failed_at" datetime not null default CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS "personal_access_tokens" ("id" integer primary key autoincrement not null, "tokenable_type" varchar not null, "tokenable_id" integer not null, "name" text not null, "token" varchar not null, "abilities" text, "last_used_at" datetime, "expires_at" datetime, "created_at" datetime, "updated_at" datetime);
INSERT INTO personal_access_tokens VALUES(6,'App\Models\User',1,'auth_token','2124ab2c03a189ddc77a2c4e0ad23d242613a67a0a2c6c2b2b29ed5a54dd95e3','["*"]',NULL,NULL,'2026-10-04 16:42:07','2026-10-04 16:42:07');
INSERT INTO personal_access_tokens VALUES(7,'App\Models\User',2,'auth_token','4bd08ac7fca602e27b86dfc0dfec3d0d92016a4966635dbc019302ee510e44c0','["*"]',NULL,NULL,'2026-10-04 16:42:15','2026-10-04 16:42:15');
INSERT INTO personal_access_tokens VALUES(8,'App\Models\User',4,'auth_token','9b2d30bb93ba7a262895e7e627c2d9eb3c5ba5226fad6b25caa5a367e12ef7e2','["*"]',NULL,NULL,'2026-10-04 16:42:15','2026-10-04 16:42:15');
CREATE TABLE IF NOT EXISTS "notifications" ("id" varchar not null, "type" varchar not null, "notifiable_type" varchar not null, "notifiable_id" integer not null, "data" text not null, "read_at" datetime, "created_at" datetime, "updated_at" datetime, primary key ("id"));
CREATE TABLE IF NOT EXISTS "roles" ("id" integer primary key autoincrement not null, "name" varchar not null, "label" varchar, "created_at" datetime, "updated_at" datetime);
INSERT INTO roles VALUES(1,'admin','Administrator','2026-10-03 16:32:53','2026-10-03 16:32:53');
INSERT INTO roles VALUES(2,'recruiter','Recruiter','2026-10-03 16:32:53','2026-10-03 16:32:53');
INSERT INTO roles VALUES(3,'candidate','Candidate','2026-10-03 16:32:53','2026-10-03 16:32:53');
CREATE TABLE IF NOT EXISTS "users" ("id" integer primary key autoincrement not null, "name" varchar not null, "email" varchar not null, "email_verified_at" datetime, "password" varchar not null, "remember_token" varchar, "created_at" datetime, "updated_at" datetime, "role_id" integer, "phone" varchar, foreign key("role_id") references "roles"("id") on delete set null);
INSERT INTO users VALUES(1,'Namanpreet Kaur','admin@talentflow.test',NULL,'$2y$12$3K0ax55hKFYx12fq24J26.pI5PImvFSg5QeO3m3uoVY/zwieKns6m',NULL,'2026-10-03 16:32:53','2026-10-04 16:41:47',1,'+1-555-0100');
INSERT INTO users VALUES(2,'Chandan Kumar','recruiter@talentflow.test',NULL,'$2y$12$3K0ax55hKFYx12fq24J26.pI5PImvFSg5QeO3m3uoVY/zwieKns6m',NULL,'2026-10-03 16:32:53','2026-10-04 16:41:47',2,'+1-555-0101');
INSERT INTO users VALUES(4,'Parampreet Singh','candidate@talentflow.test',NULL,'$2y$12$3K0ax55hKFYx12fq24J26.pI5PImvFSg5QeO3m3uoVY/zwieKns6m',NULL,'2026-10-04 16:41:47','2026-10-04 16:41:47',3,'+1-555-0201');
INSERT INTO users VALUES(5,'Namanpreet Kaur1','namansaini960@gmail.com',NULL,'$2y$12$WmA2zKFDvmZFrW8GnCkGqOU9MA.lUNrVDpMUxHR30Bw9rt289UUfe',NULL,'2026-10-04 16:47:49','2026-10-04 16:47:49',3,'+918847460756');
INSERT INTO users VALUES(6,'pp','pp@gmail.com',NULL,'$2y$12$xfO3gWLy7MraS4oS8HQ9Nerp9k3Rz7Zt3QTFGHtiuztppyO0uYKDK',NULL,'2026-10-04 16:59:47','2026-10-04 16:59:47',3,'1234567899');
CREATE TABLE IF NOT EXISTS "skills" ("id" integer primary key autoincrement not null, "name" varchar not null, "created_at" datetime, "updated_at" datetime);
INSERT INTO skills VALUES(1,'PHP','2026-10-03 16:32:53','2026-10-03 16:32:53');
INSERT INTO skills VALUES(2,'Laravel','2026-10-03 16:32:53','2026-10-03 16:32:53');
INSERT INTO skills VALUES(3,'MySQL','2026-10-03 16:32:53','2026-10-03 16:32:53');
INSERT INTO skills VALUES(4,'Vue.js','2026-10-03 16:32:53','2026-10-03 16:32:53');
INSERT INTO skills VALUES(5,'React','2026-10-03 16:32:53','2026-10-03 16:32:53');
INSERT INTO skills VALUES(6,'Docker','2026-10-03 16:32:53','2026-10-03 16:32:53');
INSERT INTO skills VALUES(7,'AWS','2026-10-03 16:32:53','2026-10-03 16:32:53');
INSERT INTO skills VALUES(8,'Git','2026-10-03 16:32:53','2026-10-03 16:32:53');
INSERT INTO skills VALUES(9,'REST API','2026-10-03 16:32:53','2026-10-03 16:32:53');
INSERT INTO skills VALUES(10,'TailwindCSS','2026-10-03 16:32:53','2026-10-03 16:32:53');
INSERT INTO skills VALUES(11,'TypeScript','2026-10-03 16:32:53','2026-10-03 16:32:53');
INSERT INTO skills VALUES(12,'Redis','2026-10-03 16:32:53','2026-10-03 16:32:53');
INSERT INTO skills VALUES(13,'Python','2026-10-03 16:32:53','2026-10-03 16:32:53');
CREATE TABLE IF NOT EXISTS "jobs" ("id" integer primary key autoincrement not null, "recruiter_id" integer not null, "title" varchar not null, "department" varchar not null, "description" text not null, "experience" varchar not null, "salary_range" varchar, "application_deadline" date not null, "status" varchar not null default 'open', "created_at" datetime, "updated_at" datetime, foreign key("recruiter_id") references "users"("id") on delete cascade);
CREATE TABLE IF NOT EXISTS "job_skills" ("id" integer primary key autoincrement not null, "job_id" integer not null, "skill_id" integer not null, "is_mandatory" tinyint(1) not null default '1', "created_at" datetime, "updated_at" datetime, foreign key("job_id") references "jobs"("id") on delete cascade, foreign key("skill_id") references "skills"("id") on delete cascade);
CREATE TABLE IF NOT EXISTS "candidates" ("id" integer primary key autoincrement not null, "user_id" integer, "name" varchar not null, "email" varchar not null, "phone" varchar, "experience_years" numeric not null default '0', "education" varchar, "skills_summary" text, "created_at" datetime, "updated_at" datetime, foreign key("user_id") references "users"("id") on delete set null);
INSERT INTO candidates VALUES(2,4,'Parampreet Singh','candidate@talentflow.test','+1-555-0201',5,'Bachelor of Computer Science','PHP, Laravel, MySQL, REST API, Docker, Vue.js','2026-10-04 16:41:47','2026-10-04 16:41:47');
INSERT INTO candidates VALUES(3,5,'Namanpreet Kaur1','namansaini960@gmail.com','+918847460756',0,NULL,NULL,'2026-10-04 16:47:49','2026-10-04 16:47:49');
INSERT INTO candidates VALUES(4,6,'pp','pp@gmail.com','1234567899',0,NULL,NULL,'2026-10-04 16:59:47','2026-10-04 16:59:47');
CREATE TABLE IF NOT EXISTS "resumes" ("id" integer primary key autoincrement not null, "candidate_id" integer not null, "file_path" varchar not null, "file_name" varchar not null, "file_size" integer, "parsed_text" text, "parsed_data" text, "status" varchar not null default 'uploaded', "created_at" datetime, "updated_at" datetime, foreign key("candidate_id") references "candidates"("id") on delete cascade);
CREATE TABLE IF NOT EXISTS "applications" ("id" integer primary key autoincrement not null, "job_id" integer not null, "candidate_id" integer not null, "resume_id" integer, "status" varchar not null default 'Applied', "skill_score" numeric not null default '0', "notes" text, "created_at" datetime, "updated_at" datetime, foreign key("job_id") references "jobs"("id") on delete cascade, foreign key("candidate_id") references "candidates"("id") on delete cascade, foreign key("resume_id") references "resumes"("id") on delete set null);
CREATE TABLE IF NOT EXISTS "application_status_histories" ("id" integer primary key autoincrement not null, "application_id" integer not null, "from_status" varchar, "to_status" varchar not null, "changed_by_user_id" integer, "comment" text, "created_at" datetime, "updated_at" datetime, foreign key("application_id") references "applications"("id") on delete cascade, foreign key("changed_by_user_id") references "users"("id") on delete set null);
CREATE TABLE IF NOT EXISTS "interviews" ("id" integer primary key autoincrement not null, "application_id" integer not null, "interviewer_id" integer not null, "scheduled_at" datetime not null, "meeting_link" varchar not null, "status" varchar not null default 'scheduled', "feedback" text, "created_at" datetime, "updated_at" datetime, foreign key("application_id") references "applications"("id") on delete cascade, foreign key("interviewer_id") references "users"("id") on delete cascade);
CREATE TABLE IF NOT EXISTS "technical_tasks" ("id" integer primary key autoincrement not null, "application_id" integer not null, "assigned_by_user_id" integer not null, "title" varchar not null, "description" text not null, "deadline" datetime not null, "status" varchar not null default 'Pending', "reminder_sent_at" datetime, "created_at" datetime, "updated_at" datetime, "attachments" text, foreign key("application_id") references "applications"("id") on delete cascade, foreign key("assigned_by_user_id") references "users"("id") on delete cascade);
CREATE TABLE IF NOT EXISTS "task_submissions" ("id" integer primary key autoincrement not null, "technical_task_id" integer not null, "repository_url" varchar, "notes" text, "file_path" varchar, "submitted_at" datetime not null, "score" integer, "feedback" text, "created_at" datetime, "updated_at" datetime, foreign key("technical_task_id") references "technical_tasks"("id") on delete cascade);
INSERT INTO sqlite_sequence VALUES('migrations',19);
INSERT INTO sqlite_sequence VALUES('users',6);
INSERT INTO sqlite_sequence VALUES('roles',3);
INSERT INTO sqlite_sequence VALUES('candidates',4);
INSERT INTO sqlite_sequence VALUES('skills',13);
INSERT INTO sqlite_sequence VALUES('personal_access_tokens',12);
CREATE INDEX "sessions_user_id_index" on "sessions" ("user_id");
CREATE INDEX "sessions_last_activity_index" on "sessions" ("last_activity");
CREATE INDEX "cache_expiration_index" on "cache" ("expiration");
CREATE INDEX "cache_locks_expiration_index" on "cache_locks" ("expiration");
CREATE INDEX "queue_jobs_queue_index" on "queue_jobs" ("queue");
CREATE INDEX "failed_jobs_connection_queue_failed_at_index" on "failed_jobs" ("connection", "queue", "failed_at");
CREATE UNIQUE INDEX "failed_jobs_uuid_unique" on "failed_jobs" ("uuid");
CREATE INDEX "personal_access_tokens_tokenable_type_tokenable_id_index" on "personal_access_tokens" ("tokenable_type", "tokenable_id");
CREATE UNIQUE INDEX "personal_access_tokens_token_unique" on "personal_access_tokens" ("token");
CREATE INDEX "personal_access_tokens_expires_at_index" on "personal_access_tokens" ("expires_at");
CREATE INDEX "notifications_notifiable_type_notifiable_id_index" on "notifications" ("notifiable_type", "notifiable_id");
CREATE UNIQUE INDEX "roles_name_unique" on "roles" ("name");
CREATE UNIQUE INDEX "users_email_unique" on "users" ("email");
CREATE UNIQUE INDEX "skills_name_unique" on "skills" ("name");
CREATE UNIQUE INDEX "job_skills_job_id_skill_id_unique" on "job_skills" ("job_id", "skill_id");
CREATE INDEX "candidates_email_index" on "candidates" ("email");
CREATE UNIQUE INDEX "applications_job_id_candidate_id_unique" on "applications" ("job_id", "candidate_id");
CREATE INDEX "jobs_status_index" on "jobs" ("status");
CREATE INDEX "jobs_department_index" on "jobs" ("department");
CREATE INDEX "jobs_recruiter_id_index" on "jobs" ("recruiter_id");
CREATE INDEX "applications_status_index" on "applications" ("status");
CREATE INDEX "applications_candidate_id_index" on "applications" ("candidate_id");
CREATE INDEX "resumes_candidate_id_index" on "resumes" ("candidate_id");
CREATE INDEX "resumes_status_index" on "resumes" ("status");
CREATE INDEX "application_status_histories_application_id_index" on "application_status_histories" ("application_id");
CREATE INDEX "interviews_scheduled_at_index" on "interviews" ("scheduled_at");
CREATE INDEX "interviews_status_index" on "interviews" ("status");
CREATE INDEX "interviews_interviewer_id_index" on "interviews" ("interviewer_id");
CREATE INDEX "interviews_application_id_index" on "interviews" ("application_id");
CREATE INDEX "technical_tasks_deadline_index" on "technical_tasks" ("deadline");
CREATE INDEX "technical_tasks_status_index" on "technical_tasks" ("status");
CREATE INDEX "technical_tasks_assigned_by_user_id_index" on "technical_tasks" ("assigned_by_user_id");
CREATE INDEX "technical_tasks_application_id_index" on "technical_tasks" ("application_id");
CREATE INDEX "task_submissions_technical_task_id_index" on "task_submissions" ("technical_task_id");
COMMIT;
